# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-06 19:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


def load_plans(apps, schema_editor):
    Plan = apps.get_model("users", "Plan")
    plan_free = Plan(id=1, name="FREE", plan_type="free_monthly", interval="monthly", amount=0, currency="USD",
                     description="Free plan", trial_period_days=0)
    plan_free.save()
    plan_pro = Plan(id=2, name="PRO", plan_type="pro_monthly", interval="monthly", amount=50, currency="USD",
                    description="Pro plan", trial_period_days=30)
    plan_pro.save()
    plan_premium = Plan(id=3, name="PREMIUM", plan_type="premium_monthly", interval="monthly", amount=250,
                        currency="USD", description="Premium plan", trial_period_days=30)
    plan_premium.save()


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0027_auto_20160826_0716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('plan_type', models.CharField(max_length=32)),
                ('interval', models.CharField(max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('currency', models.CharField(max_length=32)),
                ('description', models.CharField(blank=True, max_length=20, null=True)),
                ('trial_period_days', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StripeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=32, null=True)),
                ('subscription_id', models.CharField(blank=True, max_length=32, null=True)),
                ('stripe_email', models.EmailField(default=b'', max_length=254)),
                ('card_last_digits', models.CharField(blank=True, max_length=4, null=True)),
                ('is_cancel', models.BooleanField(default=False)),
                ('renew_date', models.DateTimeField(blank=True, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE,
                                           related_name='user_plan_id', to='users.Plan')),
                ('user',
                 models.ForeignKey(max_length=16, on_delete=django.db.models.deletion.CASCADE, related_name='user_id',
                                   to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(load_plans),
    ]
