# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-16 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_plan_stripedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=32)),
                ('event_type', models.CharField(blank=True, max_length=32, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=32, null=True)),
                ('event', jsonfield.fields.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
