# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-20 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_stripewebhook'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripedetails',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
    ]
