# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-02 10:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_stripedetails_discount_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
