# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-11 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_company_is_private'),
    ]

    operations = [
        migrations.CreateModel(
            name='MemberInvitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_id', models.IntegerField()),
                ('member_email', models.EmailField(default=b'', max_length=254)),
            ],
        ),
    ]
