# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-28 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_plan_data_no_trial'),
        ('users', '0033_plan_data'),
    ]

    operations = [
    ]
